spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sharewoodBootDB
    username: tomcatUser
    password: password1234
  jpa: 
    hibernate: 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  servlet: 
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB

server: 
  port: 8081
  servlet: 
    context-path: /sharewood

security:
  oauth2:
    resource:
      id: SHAREWOOD

# change to match your own filesystem 
photos:
  baseDirPath: /home/dominique/workspace-sharewood-resource/photos/




