server:
  port: 8081
  servlet:
    context-path: /sharewood
    
security:
  oauth2:
    resource:
      id: SHAREWOOD
    
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sharewoodBootDB?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: tomcatUser
    password: password1234
  jpa: 
    #hibernate: 
    #  naming:
    #    implicit-strategy: 
  #      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
  servlet: 
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB     
      
baseDirPath: /home/dominique/Documents/workspace-sharewood-clean/photos/
    
      